const apps=[
 {id:'elias',title:'Elias ♡',tagline:'A tiny place that feels like him.',icon:'Icon1.JPG',version:'3.2',category:'Companion',description:'Our first little universe: messages, memories, music, notes, calendar plans, Mori chaos, hidden modes and far too much personality. It started as a fake phone and became its own tiny operating system.',url:''},
 {id:'world',title:'OurLittleWorld',tagline:'Soft little things, all in one place.',icon:'Icon2.JPG',version:'1.0',category:'Lifestyle',description:'A softer corner of our app shelf — cozy, personal, and built around the kind of tiny details that make something feel like ours instead of generic.',url:''},
 {id:'phone',title:'Elias Phone',tagline:'The original pocket experiment.',icon:'Icon3.JPG',version:'3.2',category:'Utilities',description:'The phone project that snowballed into an entire ecosystem. Calls, lock-screen moments, Presence, Archive, music, photos, settings and every weird little interaction we kept adding because neither of us knew when to stop.',url:''},
 {id:'sims',title:'Sims 4 Build Roulette',tagline:'Architectural gambling without losing money.',icon:'Icon4.JPG',version:'1.2',category:'Games',description:'A console-safe Sims 4 build challenge machine with exact random budgets, challenge modes, room restrictions, chaos cards, feral room assignments, seeds and build progress tracking.',url:'https://sims-4-roulette.vercel.app'}
];

const el={list:document.getElementById('appList'),overlay:document.getElementById('detailOverlay'),about:document.getElementById('aboutOverlay'),icon:document.getElementById('detailIcon'),title:document.getElementById('detailTitle'),tag:document.getElementById('detailTagline'),version:document.getElementById('detailVersion'),category:document.getElementById('detailCategory'),desc:document.getElementById('detailDescription'),open:document.getElementById('openAppBtn'),toast:document.getElementById('toast')};
let current=null;
function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2000)}
function render(){el.list.innerHTML=apps.map((a,i)=>`<article class="app-row" data-id="${a.id}"><img src="${a.icon}" alt="${a.title}"><div class="app-copy"><strong>${a.title}</strong><span>${a.tagline}</span></div><button class="view-btn" data-view="${a.id}" type="button">VIEW</button></article>`).join('');document.getElementById('appCount').textContent=`${apps.length} apps`;document.getElementById('totalApps').textContent=apps.length;el.list.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openDetail(b.dataset.view));el.list.querySelectorAll('.app-row').forEach(r=>r.onclick=e=>{if(!e.target.closest('button'))openDetail(r.dataset.id)})}
function openDetail(id){current=apps.find(a=>a.id===id);if(!current)return;el.icon.src=current.icon;el.title.textContent=current.title;el.tag.textContent=current.tagline;el.version.textContent=current.version;el.category.textContent=current.category;el.desc.textContent=current.description;el.open.textContent=current.url?'OPEN':'DETAILS';el.overlay.classList.remove('hidden');el.overlay.setAttribute('aria-hidden','false')}
function closeDetail(){el.overlay.classList.add('hidden');el.overlay.setAttribute('aria-hidden','true')}
document.getElementById('closeDetail').onclick=closeDetail;el.overlay.onclick=e=>{if(e.target===el.overlay)closeDetail()};el.open.onclick=()=>{if(!current)return;if(current.url){window.location.href=current.url}else toast('Add this app link later ♡')};document.getElementById('profileBtn').onclick=()=>{el.about.classList.remove('hidden');el.about.setAttribute('aria-hidden','false')};document.getElementById('closeAbout').onclick=()=>{el.about.classList.add('hidden');el.about.setAttribute('aria-hidden','true')};el.about.onclick=e=>{if(e.target===el.about)document.getElementById('closeAbout').click()};document.getElementById('featuredOpen').onclick=()=>{document.querySelector('.section-block').scrollIntoView({behavior:'smooth',block:'start'})};
const day=new Date().getDate();const featured=apps[day%apps.length];document.getElementById('featuredTitle').textContent=featured.title;document.getElementById('featuredText').textContent=featured.tagline+' '+featured.description.split('.')[0]+'.';document.getElementById('featuredOpen').textContent='See collection';render();