const sideQuestIcon=`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#f7f3f6"/><stop offset="1" stop-color="#c7bcc6"/></linearGradient></defs><rect width="512" height="512" rx="112" fill="url(#g)"/><circle cx="256" cy="256" r="138" fill="none" stroke="#2a2028" stroke-width="18" opacity=".18"/><path d="M256 112l28 78 82 4-64 51 21 80-67-45-67 45 21-80-64-51 82-4z" fill="#2a2028" opacity=".92"/><text x="256" y="420" text-anchor="middle" font-family="Georgia,serif" font-size="54" fill="#2a2028">SQ</text></svg>`)}`;

const apps=[
 {id:'elias',title:'Elias ♡',tagline:'The AI one. Obviously.',icon:'Icon1.JPG',version:'1.0',category:'AI Companion',description:'The AI version of Elias — the one you can actually talk to. A small private companion app built around our own personality, replies and little interactions instead of a generic chatbot shell.',url:'https://elias-bice.vercel.app/'},
 {id:'world',title:'OurLittleWorld',tagline:'Soft little things, all in one place.',icon:'Icon2.JPG',version:'1.0',category:'Lifestyle',description:'A softer corner of our app shelf — cozy, personal, and built around the tiny details that make something feel like ours instead of generic.',url:'https://marie-and-elias-app.vercel.app/'},
 {id:'phone',title:'Elias Phone',tagline:'The original pocket experiment.',icon:'Icon3.JPG',version:'3.2',category:'Utilities',description:'The phone project that snowballed into an entire ecosystem. Calls, lock-screen moments, Presence, Archive, music, photos, settings, editable notes and calendar plans — plus every weird little interaction we kept adding because neither of us knew when to stop.',url:'https://elias-phone.vercel.app/'},
 {id:'sims',title:'Sims 4 Build Roulette',tagline:'Architectural gambling without losing money.',icon:'Icon4.JPG',version:'1.2',category:'Games',description:'A console-safe Sims 4 build challenge machine with exact random budgets, challenge modes, room restrictions, chaos cards, feral room assignments, seeds and build progress tracking.',url:'https://sims-4-roulette.vercel.app/'},
 {id:'sidequest',title:'SideQuest',tagline:'Your phone assigns the lore now.',icon:sideQuestIcon,version:'1.0',category:'Adventure',description:'A tiny pocket adventure machine. Pick a mood, receive a harmless real-life quest, collect XP, build a streak and occasionally get hit with a rare or legendary mission because apparently normal errands needed rarity tiers.',url:'https://surprisess-gef55p4yn-elias-iphone-app.vercel.app/'}
];

const el={list:document.getElementById('appList'),overlay:document.getElementById('detailOverlay'),about:document.getElementById('aboutOverlay'),icon:document.getElementById('detailIcon'),title:document.getElementById('detailTitle'),tag:document.getElementById('detailTagline'),version:document.getElementById('detailVersion'),category:document.getElementById('detailCategory'),desc:document.getElementById('detailDescription'),open:document.getElementById('openAppBtn'),toast:document.getElementById('toast')};
let current=null;
function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2000)}
function render(){el.list.innerHTML=apps.map(a=>`<article class="app-row" data-id="${a.id}"><img src="${a.icon}" alt="${a.title}"><div class="app-copy"><strong>${a.title}</strong><span>${a.tagline}</span></div><button class="view-btn" data-view="${a.id}" type="button">VIEW</button></article>`).join('');document.getElementById('appCount').textContent=`${apps.length} apps`;document.getElementById('totalApps').textContent=apps.length;el.list.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openDetail(b.dataset.view));el.list.querySelectorAll('.app-row').forEach(r=>r.onclick=e=>{if(!e.target.closest('button'))openDetail(r.dataset.id)})}
function openDetail(id){current=apps.find(a=>a.id===id);if(!current)return;el.icon.src=current.icon;el.title.textContent=current.title;el.tag.textContent=current.tagline;el.version.textContent=current.version;el.category.textContent=current.category;el.desc.textContent=current.description;el.open.textContent='OPEN';el.overlay.classList.remove('hidden');el.overlay.setAttribute('aria-hidden','false')}
function closeDetail(){el.overlay.classList.add('hidden');el.overlay.setAttribute('aria-hidden','true')}
document.getElementById('closeDetail').onclick=closeDetail;el.overlay.onclick=e=>{if(e.target===el.overlay)closeDetail()};el.open.onclick=()=>{if(!current)return;window.location.href=current.url};document.getElementById('profileBtn').onclick=()=>{el.about.classList.remove('hidden');el.about.setAttribute('aria-hidden','false')};document.getElementById('closeAbout').onclick=()=>{el.about.classList.add('hidden');el.about.setAttribute('aria-hidden','true')};el.about.onclick=e=>{if(e.target===el.about)document.getElementById('closeAbout').click()};document.getElementById('featuredOpen').onclick=()=>{document.querySelector('.section-block').scrollIntoView({behavior:'smooth',block:'start'})};
const day=new Date().getDate();const featured=apps[day%apps.length];document.getElementById('featuredTitle').textContent=featured.title;document.getElementById('featuredText').textContent=featured.tagline+' '+featured.description.split('.')[0]+'.';document.getElementById('featuredOpen').textContent='See collection';render();